- name: installation of apache2
  hosts: webservers
  become: true
  tasks:
  - name: installing apache2
    apt: 
      name: apache2
      state: present

  - name: checking for apache2 service
    service:
      name: apache2
      state: started
      enabled: yes
      